name: Build and Deploy AI Coder

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop my-ai-coder || true
            docker rm my-ai-coder || true
            docker run -d \
              --name my-ai-coder \
              --network my-shared-network \
              -p 8003:3000 \
              -e "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" \
              --restart always \
              ghcr.io/${{ github.repository }}:latest

